[package]
name = "mydbg"
version = "0.1.0"
authors = ["pzhxbz <pzhxbz@qq.com>"]
edition = "2021"

[workspace]
members = [
    "dbg_core",
    "dbg_gui",
]


[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
rpath = true